import Head from "next/head";
import {
  ScatterChart,
  Scatter,
  XAxis,
  YAxis,
  Tooltip,
  ZAxis,
  ReferenceLine,
  LabelList,
  ResponsiveContainer
} from "recharts";

export default function Home() {
  const data = [
    { con_dig: 10, pro_dig: 30, ada: (10 + 40) / 2, fecha: 'Ene 3 2022' },
    { con_dig: 30, pro_dig: 100 , ada: (30 + 100) / 2, fecha: 'Ene 23 2022' },
    { con_dig: 5, pro_dig: 80, ada: (5 + 80) / 2, fecha: 'Feb 10 2022' },
    { con_dig: 50, pro_dig: 100, ada: (50 + 100) / 2, fecha: 'Mar 2 2022' },
    { con_dig: 70, pro_dig: 90, ada: (70+ 100) / 2, fecha: 'Mar 29 2022' },
    { con_dig: 100, pro_dig: 60, ada: (100 + 100) / 2, fecha: 'Abr 10 2022' },
  ];

  const CustomTooltip = ({ active, payload, label }) => {
    if (active && payload && payload.length) {
      return (
        <div style={{fontSize: '12px', backgroundColor: '#ffffff', padding:'4px 4px 4px 4px', border: 'solid .5px #c4c4c4', lineHeight: '.5rem'}}>
          <p><strong>Fecha</strong>{`: ${payload[0].payload.fecha}`}</p>
          <p><strong>Adaptabilidad Digital</strong>{`: ${payload[2].value}`}</p>
          <p>Autoconfianza Digital{`: ${payload[0].value}`}</p>
          <p>Proactividad Digital{`: ${payload[1].value}`}</p>
        </div>
      );
    }
  
    return null;
  };

  return (
    <div style={{ padding: "20px" }}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <h1>Prueba DAD</h1>
        <div>
          <h4>Data:</h4>
          <div style={{ backgroundColor: '#f1f1f1', padding:'4px', fontSize:13 }}>
            { data.map((item, index) => <div key={index} style={{ display: "flex", gap:"30px"}}>
                <div style={{ width:'100px' }}>{`con_dig: ${item.con_dig}`}</div>
                <div style={{ width:'100px' }}>{`pro_dig: ${item.pro_dig}`}</div>
                <div style={{ width:'100px' }}>{`DAD: ${item.ada}`}</div>
                <div style={{ width:'200px' }}>{`fecha: ${item.fecha}`}</div>
            </div>)}
          </div>
        </div>
        <div style={{ width:'50%', height:400, marginTop:'40px' }}>
          <ResponsiveContainer>
            <ScatterChart
              margin={{
                top: 20,
                right: 30,
                bottom: 20,
                left: 10,
              }}
            >
              {/* <ReferenceLine x={100} stroke="gray" />
              <ReferenceLine y={60} label="Abr 10 2022"  stroke="gray" /> */}
              {/* <CartesianGrid /> */}
              {/* 
              <ReferenceLine y={30} label="min" stroke="red" /> */}
              {/* <XAxis type="number" dataKey="con_dig" style={{ fontSize:'12px' }} label={{ value: 'Autoconfianza Digital', position: 'insideBottom', offset: -10 }} name="Autoconfianza Digital" />
              <YAxis type="number" dataKey="pro_dig" style={{ fontSize:'12px' }} label={{ value: 'Proactividad Digital', angle: -90, position: 'insideBottomLeft'}} name="Proactividad Digital" />
              <ZAxis dataKey="ada" name="Adaptabilidad Digital"/>
            <Tooltip cursor={{ strokeDasharray: "2 2", stroke: '#00DFDF', strokeWidth: 2 }} itemStyle={{ fontSize:'12px' }} /> */}
              <XAxis type="number" dataKey="con_dig" style={{ fontSize:'12px' }} label={{ value: 'Autoconfianza Digital', position: 'insideBottom', offset: -10 }} name="Autoconfianza Digital" />
              <YAxis type="number" dataKey="pro_dig" style={{ fontSize:'12px' }} label={{ value: 'Proactividad Digital', angle: -90, position: 'insideBottomLeft'}} name="Proactividad Digital" />
              <ZAxis dataKey="ada"  name="Adaptabilidad Digital"/>
              <Tooltip content={<CustomTooltip />} cursor={{ strokeDasharray: "2 2", stroke: '#00DFDF', strokeWidth: 2 }} />
              <Scatter name="A school" data={data} fill="#FE01A4" line={{ strokeWidth: 1}} />
            </ScatterChart>
          </ResponsiveContainer>
        </div>
      </div>

      
    </div>
  );
}
